language: php

jobs:
  include:
#    - php: 5.6
#    - php: 7.0
#    - php: 7.1
#    - php: 7.2
#    - php: 7.3
#    - php: 7.4
    - php: 7.4
      env: gp_data_type=.json


# phpunit 8 will result in an error
# https://www.reddit.com/r/PHPhelp/comments/apipqs/travis_specifying_phpunit_version/
before_script:
  - composer init -n
  - composer require phpunit/phpunit "<8 >=4"
  - composer require symfony/process
  - composer require guzzlehttp/guzzle
  - composer require phpunit/php-code-coverage "<7" # for phpunit compat
  #- phpenv config-add phpunit/phpconfig.ini

script:
  - vendor/bin/phpunit
  - php phpunit/ServerCombineCoverage.php
  - bash <(curl -s https://codecov.io/bash) -s ./x_coverage # Submit coverage report to https://codecov.io
